stages:
- name: Test
  steps:
  - runScriptConfig:
      image: node:10
      shellScript: |-
        npm install
        npm test
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: feathers-chat
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
