apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: feathers-chat
  namespace: default
  labels:
    app: feathers-chat
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: feathers-chat
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: feathers-chat
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: is_master
                operator: In
                values:
                - "false"
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - api
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: feathers-chat
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 3030