apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: feathers-chat
  namespace: default
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    app: feathers-chat
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: feathers-chat
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: is_master
                operator: In
                values:
                - "false"
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - api
      containers:
      - image: feathers-chat:latest
        imagePullPolicy: Always
        name: feathers-chat
        resources: {}
        stdin: true
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30